services:
  - type: web
    name: bias-detector
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEWSAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false